theme: jekyll-theme-cayman

# Site Settings
locale                   : "en"
title                    : "Leandro Lape単a"
title_separator          : "-"
name                     : "Leandro Lape単a"
occupation               : "Electronics Engineer"
url                      : "https://kdzmcqn.github.io/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

github:
  username               : "kdzmcqn"
  owner_name             : "Leandro Lape単a"
  owner_url              : "https://github.com/kdzmcqn"

author:
  name                   : "Leandro Lape単a"
  location               : "Manila, PH"
  email                  : "lapenaleadnro@gmail.com"

    # Google Analytics
google_analytics         : UA-180928265-1


# headers
header_nav : ["GitHub", "Twitter", "Wordpress"]

markdown: kramdown
highlighter: rouge

plugins: 
  - jekyll-mermaid
gems: [jekyll-mermaid]
mermaid:
  src: "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"

collections:
  ventures:
    output: true